### ISSUE TITLE
missing class .q1 on text elements

### ISSUE THREAD

**Issue by thomasleveil** [kamisama/cal-heatmap#143]
I'm struggling to change the text color for a cell. I could customize the background color with 

```css
.cal-heatmap-container .q2 {
  fill: rgb(249, 201, 185);
}
```

but it seems there is no way to take control of the text. I tried the following:

```css
.cal-heatmap-container .q2 + text {
  stroke: red;
}
```

Could not the `.q2` class be set on `text` elements as they are for the `rect` element?
Or am I missing something obvious?

**Comment by kamisama** [comment]
The text have the class: `.subdomain-text`. Maybe try with

```css
.cal-heatmap-container .q2 .subdomain-text {
  stroke: red;
}
```

**Comment by thomasleveil** [comment]
that doesn't work as the element with the `subdomain-text` class isn't a children of the element with the `q2` class. Here's how it is:

```html
<g>
    <rect class=" graph-rect future r1 q1" width="20" height="20" x="110" y="22"></rect>
    <title>occupé 1 réservation</title>
    <text class="subdomain-text" x="120" y="32" text-anchor="middle" dominant-baseline="central">09</text>
</g>
```

Usually the [CSS `+` operator][css+] would allow to match a sibling, but this does work in this case (maybe because of SVG?)

[css+]: https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors

**Comment by kamisama** [comment]
So, finally, it works ?

**Comment by thomasleveil** [comment]
sorry typo, it does not work

**Comment by kamisama** [comment]
Try with

```css
.cal-heatmap-container .q2 + title + .subdomain-text {
  stroke: red;
}
```
